// Auto-generated by: supabase gen types typescript
// Run: supabase gen types typescript --project-id <id> > src/types/database.ts
// TODO: regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          tier: 'free' | 'pro'
          stripe_customer_id: string | null
          queries_today: number
          queries_reset_at: string
          documents_this_month: number
          documents_reset_at: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'],
          'created_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      documents: {
        Row: {
          id: string
          user_id: string
          filename: string
          r2_key: string
          mime_type: string
          file_size_bytes: number
          status: 'processing' | 'ready' | 'error'
          page_count: number | null
          extracted_text_preview: string | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['documents']['Row'],
          'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['documents']['Insert']>
      }
      document_chunks: {
        Row: {
          id: string
          document_id: string
          user_id: string
          chunk_index: number
          content: string
          embedding: number[] | null
          token_count: number | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['document_chunks']['Row'],
          'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['document_chunks']['Insert']>
      }
      conversations: {
        Row: {
          id: string
          user_id: string
          document_id: string | null
          title: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['conversations']['Row'],
          'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['conversations']['Insert']>
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          user_id: string
          role: 'user' | 'assistant'
          content: string
          citations: Json
          model: string | null
          input_tokens: number | null
          output_tokens: number | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['messages']['Row'],
          'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['messages']['Insert']>
      }
      law_chunks: {
        Row: {
          id: string
          lovdata_url: string
          law_name: string
          section: string
          section_title: string | null
          content: string
          content_hash: string
          embedding: number[] | null
          source_url: string
          jurisdiction: string
          last_updated: string
        }
        Insert: Omit<Database['public']['Tables']['law_chunks']['Row'],
          'id' | 'last_updated'>
        Update: Partial<Database['public']['Tables']['law_chunks']['Insert']>
      }
    }
    Functions: {
      increment_queries_today: {
        Args: { user_id: string }
        Returns: void
      }
    }
  }
}
