export const nb = {
    errors: {
        generic: "Noe gikk galt. Prøv igjen.",
        rateLimit:
            "Du har brukt opp dagens gratis spørsmål. Oppgrader til Pro for ubegrenset tilgang.",
        documentProcessing:
            "Dokumentet kunne ikke behandles. Sjekk at filen er et gyldig PDF- eller Word-dokument.",
        unauthorized: "Du må logge inn for å bruke denne funksjonen.",
        fileTooLarge: "Filen er for stor. Maksimal filstørrelse er 10 MB.",
        invalidFileType: "Kun PDF- og Word-dokumenter støttes.",
        streamFailed: "Tilkoblingen til serveren ble brutt. Prøv igjen.",
        conversationLoad: "Kunne ikke laste samtalehistorikk.",
    },
    disclaimer: {
        short: "Dette er ikke juridisk rådgivning. Konsulter en advokat for bindende beslutninger.",
        persistent:
            "Juridisk AI gir ikke juridisk rådgivning. Konsulter en advokat for bindende beslutninger.",
        full: "Juridisk AI gir generell informasjon basert på norsk lov og offentlig tilgjengelig rettskildemateriale. Svarene utgjør ikke juridisk rådgivning og etablerer ikke et klient-advokat-forhold. For beslutninger med rettslige konsekvenser anbefales det alltid å konsultere en kvalifisert advokat.",
    },
    loading: {
        analyzing: "Analyserer dokumentet...",
        thinking: "Tenker...",
        retrieving: "Henter rettskilder fra Lovdata...",
        uploading: "Laster opp dokument...",
    },
    chat: {
        placeholder: "Skriv ditt juridiske spørsmål her...",
        send: "Send",
        newConversation: "Ny samtale",
        conversations: "Samtaler",
        documents: "Dokumenter",
        noConversations: "Ingen samtaler ennå.",
        uploadPrompt: "Last opp et dokument for å stille spørsmål om det.",
        upgradeToPro: "Oppgrader til Pro",
        wordmark: "Juridisk",
        emptySubtitle: "Din juridiske rådgiver, alltid tilgjengelig.",
        emptyHint: "Eller skriv ditt eget spørsmål nedenfor.",
        userLabel: "Du",
        assistantLabel: "Juridisk",
        freeUsage: "3 av 10 spørsmål i dag",
        usageToday: (used: number, limit: number) =>
            `${used} av ${limit} spørsmål i dag`,
        history: "Historikk",
        upload: "Last opp",
        today: "i dag",
        yesterday: "i går",
        loadingConversations: "Laster samtaler...",
        attachedFile: "Vedlagt fil",
        removeFile: "Fjern fil",
        openHistory: "Åpne samtalehistorikk",
        focusInput: "Gå til meldingsfelt",
        openFilePicker: "Last opp dokument",
        logout: "Logg ut",
        signedInAs: "Innlogget",
        closePanel: "Lukk panel",
        attachedDocument: "Dokument valgt",
        lovdata: "Lovdata",
        source: "Se kilde",
        dagensBruk: "Dagens bruk",
        oppgraderNa: "Oppgrader nå",
        ubegrensetTilgang: "Ubegrenset tilgang, alltid.",
        lastOppKontrakt: "Last opp en kontrakt for å komme i gang.",
        pro: "Juridisk Pro",
        suggestions: [
            "Hva må en arbeidskontrakt inneholde?",
            "Er denne NDA-en balansert?",
            "Hva er oppsigelsestiden for en fast ansatt?",
            "Trenger jeg en databehandleravtale med mine SaaS-leverandører?",
        ],
    },
    settings: {
        account: "Konto",
        title: "Innstillinger",
        currentPlan: "Nåværende abonnement",
        free: "Gratis",
        pro: "Pro",
        usageLabel: "Spørsmål brukt i dag:",
        unlimited: "ubegrenset",
        upgradePrice: "Oppgrader til Pro -- NOK 299/mnd",
        manageSubscription: "Administrer abonnement",
    },
    upload: {
        drag: "Dra og slipp PDF eller Word-dokument her",
        or: "eller",
        browse: "Velg fil",
        processing: "Behandler...",
        ready: "Klar",
        error: "Feil ved behandling",
        maxSize: "Maks 10 MB",
    },
    sidebar: {
        newConversation: "Ny samtale",
        queriesUsed: (used: number, total: number) =>
            `${used} av ${total} spørsmål i dag`,
        upgradeLink: "Oppgrader til Pro",
        conversations: "Samtaler",
        noConversations: "Ingen samtaler ennå.",
        noConversationsHint: "Last opp en kontrakt for å komme i gang.",
        userProSuffix: "Pro",
        inputDisabledPlaceholder: "Oppgrader til Pro for å fortsette.",
    },
};
